# Generated by Django 5.1 on 2024-08-25 23:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_vents', models.BigAutoField(primary_key=True, serialize=False, verbose_name='numero_venata')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2024, 8, 25, 23, 39, 13, 970420), verbose_name='fecha')),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total venta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_producto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor producto')),
                ('iva_calculado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Iva calculado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
        ),
    ]
