# Generated by Django 5.1 on 2024-08-25 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 23, 42, 24, 488677), verbose_name='fecha'),
        ),
    ]
