version: '3.8'

services:

  web:
    build: ./back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    environment:
      - TZ=America/Bogota   # Establecer la zona horaria deseada
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=prueba_back
      - POSTGRES_PASSWORD=prueba_back
      - POSTGRES_DB=prueba_back
volumes:
  postgres_data:
