# Generated by Django 5.1 on 2024-08-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Codigo', models.CharField(primary_key=True, serialize=False, verbose_name='codigo')),
                ('nombre', models.CharField(verbose_name='nombre')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.BooleanField(verbose_name='Tiene iva')),
                ('valor_iva', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
