# Generated by Django 5.1 on 2024-08-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='valor_iva',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
