# Generated by Django 5.1 on 2024-08-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('direccion', models.CharField(verbose_name='Direccion')),
                ('telefono', models.BigIntegerField(verbose_name='Telefono')),
            ],
        ),
    ]
