# Generated by Django 5.1 on 2024-08-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.BigIntegerField(verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.BigIntegerField(verbose_name='Telefono'),
        ),
    ]
